src/Web/WebMVC/ViewModels/Header.cs
using System;

namespace Microsoft.eShopOnContainers.WebMVC.ViewModels
{
    public class Header
    {
        public string Controller { get; set; }
        public string Text { get; set; }
    }
}

src/Web/WebMVC/Controllers/CatalogController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.eShopOnContainers.WebMVC.ViewModels.Pagination;
using Microsoft.eShopOnContainers.WebMVC.Services;
using Microsoft.eShopOnContainers.WebMVC.ViewModels.CatalogViewModels;

namespace Microsoft.eShopOnContainers.WebMVC.Controllers
{
    public class CatalogController : Controller
    {
        private ICatalogService _catalogSvc;

        public CatalogController(ICatalogService catalogSvc) => 
            _catalogSvc = catalogSvc;

        public async Task<IActionResult> Index(int? BrandFilterApplied, int? TypesFilterApplied, int? page)
        {
            var itemsPage = 10;
            var catalog = await _catalogSvc.GetCatalogItems(page ?? 0, itemsPage, BrandFilterApplied, TypesFilterApplied);
            var vm = new IndexViewModel()
            {
                CatalogItems = catalog.Data,
                Brands = await _catalogSvc.GetBrands(),
                Types = await _catalogSvc.GetTypes(),
                BrandFilterApplied = BrandFilterApplied ?? 0,
                TypesFilterApplied = TypesFilterApplied ?? 0,
                PaginationInfo = new PaginationInfo()
                {
                    ActualPage = page ?? 0,
                    ItemsPerPage = catalog.Data.Count,
                    TotalItems = catalog.Count, 
                    TotalPages = (int)Math.Ceiling(((decimal)catalog.Count / itemsPage))
                }
            };

            vm.PaginationInfo.Next = (vm.PaginationInfo.ActualPage == vm.PaginationInfo.TotalPages - 1) ? "is-disabled" : "";
            vm.PaginationInfo.Previous = (vm.PaginationInfo.ActualPage == 0) ? "is-disabled" : "";

            return View(vm);
        }
    }
}

src/Web/WebMVC/Views/Shared/_Header.cshtml
@model IEnumerable<Microsoft.eShopOnContainers.WebMVC.ViewModels.Header>

<div class="esh-header">
    <div class="container">
        @foreach (var header in @Model)
        {
            <a class="esh-header-back" asp-area="" asp-controller="@header.Controller" asp-action="Index">@header.Text</a>
        }
    </div>
</div>

src/Web/WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Microsoft.eShopOnContainers.WebMVC</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/app.css" />
        <link rel="stylesheet" href="~/css/app.component.css" />
        <link rel="stylesheet" href="~/css/shared/components/header/header.css" />
        <link rel="stylesheet" href="~/css/shared/components/identity/identity.css" />
        <link rel="stylesheet" href="~/css/shared/components/pager/pager.css" />
        <link rel="stylesheet" href="~/css/basket/basket.component.css" />
        <link rel="stylesheet" href="~/css/campaigns/campaigns.component.css" />
        <link rel="stylesheet" href="~/css/basket/basket-status/basket-status.component.css" />
        <link rel="stylesheet" href="~/css/catalog/catalog.component.css" />
        <link rel="stylesheet" href="~/css/orders/orders.component.css" />
        <link rel="stylesheet" href="~/css/orders/orders-detail/orders-detail.component.css" />
        <link rel="stylesheet" href="~/css/orders/orders-new/orders-new.component.css" />
        <link rel="stylesheet" href="~/css/override.css" type="text/css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/override.css" type="text/css" />
    </environment>
</head>
<body>
    <header class="navbar navbar-light navbar-static-top">
        <div class="container">
            <article class="row">

                <section class="col-lg-7 col-md-6 col-xs-12">
                    <a class="navbar-brand" routerLink="catalog">
                        <a asp-area="" asp-controller="Catalog" asp-action="Index">
                            <img src="~/images/brand.png" />
                        </a>
                </section>

                @await Html.PartialAsync("_LoginPartial")
            </article>
        </div>
    </header>

    @RenderBody()


    <footer class="esh-app-footer">
        <div class="container">
            <article class="row">

                <section class="col-sm-6">
                    <img class="esh-app-footer-brand" src="~/images/brand_dark.png" />
                </section>

                <section class="col-sm-6">
                    <img class="esh-app-footer-text hidden-xs" src="~/images/main_footer_text.png" width="335" height="26" alt="footer text image" />
                </section>

            </article>
        </div>
    </footer>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>