src/Web/WebMVC/ViewModels/Catalog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Microsoft.eShopOnContainers.WebMVC.ViewModels
{
    public class Catalog
    {
        public int PageIndex { get; set; }
        public int PageSize { get; set; }
        public int Count { get; set; }
        public List<CatalogItem> Data { get; set; }
    }
}

src/Web/WebMVC/ViewModels/Pagination/PaginationInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Microsoft.eShopOnContainers.WebMVC.ViewModels.Pagination
{
    public class PaginationInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int ActualPage { get; set; }
        public int TotalPages { get; set; }
        public string Previous { get; set; }
        public string Next { get; set; }
    }
}

src/Web/WebMVC/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.eShopOnContainers.WebMVC.Services;
using Microsoft.eShopOnContainers.WebMVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Polly.CircuitBreaker;

namespace Microsoft.eShopOnContainers.WebMVC.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IBasketService _basketSvc;
        private readonly ICatalogService _catalogSvc;
        private readonly IIdentityParser<ApplicationUser> _appUserParser;

        public CartController(IBasketService basketSvc, ICatalogService catalogSvc, IIdentityParser<ApplicationUser> appUserParser)
        {
            _basketSvc = basketSvc;
            _catalogSvc = catalogSvc;
            _appUserParser = appUserParser;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var user = _appUserParser.Parse(HttpContext.User);
                var vm = await _basketSvc.GetBasket(user);

                return View(vm);
            }
            catch (BrokenCircuitException)
            {
                // Catch error when Basket.api is in circuit-opened mode                 
                HandleBrokenCircuitException();
            }

            return View();
        }

        
        [HttpPost]
        public async Task<IActionResult> Index(Dictionary<string, int> quantities, string action)
        {
            try
            {
                var user = _appUserParser.Parse(HttpContext.User);
                var basket = await _basketSvc.SetQuantities(user, quantities);
                var vm = await _basketSvc.UpdateBasket(basket);

                if (action == "[ Checkout ]")
                {
                    var order = _basketSvc.MapBasketToOrder(basket);
                    return RedirectToAction("Create", "Order");
                }
            }
            catch (BrokenCircuitException)
            {
                // Catch error when Basket.api is in circuit-opened mode                 
                HandleBrokenCircuitException();
            }

            return View();
        }

        public async Task<IActionResult> AddToCart(CatalogItem productDetails)
        {
            try
            {
                if (productDetails.Id != null)
                {
                    var user = _appUserParser.Parse(HttpContext.User);
                    var product = new BasketItem()
                    {
                        Id = Guid.NewGuid().ToString(),
                        Quantity = 1,
                        ProductName = productDetails.Name,
                        PictureUrl = productDetails.PictureUri,
                        UnitPrice = productDetails.Price,
                        ProductId = productDetails.Id
                    };
                    await _basketSvc.AddItemToBasket(user, product);
                }
                return RedirectToAction("Index", "Catalog");            
            }
            catch (BrokenCircuitException)
            {
                // Catch error when Basket.api is in circuit-opened mode                 
                HandleBrokenCircuitException();
            }

            return RedirectToAction("Index", "Catalog");
        }

        private void HandleBrokenCircuitException()
        {
            TempData["BasketInoperativeMsg"] = "Basket Service is inoperative, please try later on. (Business Msg Due to Circuit-Breaker)";
        }
    }
}

src/Web/WebMVC/Controllers/CatalogController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.eShopOnContainers.WebMVC.ViewModels.Pagination;
using Microsoft.eShopOnContainers.WebMVC.Services;
using Microsoft.eShopOnContainers.WebMVC.ViewModels.CatalogViewModels;

namespace Microsoft.eShopOnContainers.WebMVC.Controllers
{
    public class CatalogController : Controller
    {
        private ICatalogService _catalogSvc;

        public CatalogController(ICatalogService catalogSvc) => 
            _catalogSvc = catalogSvc;

        public async Task<IActionResult> Index(int? BrandFilterApplied, int? TypesFilterApplied, int? page)
        {
            var itemsPage = 10;
            var catalog = await _catalogSvc.GetCatalogItems(page ?? 0, itemsPage, BrandFilterApplied, TypesFilterApplied);
            var vm = new IndexViewModel()
            {
                CatalogItems = catalog.Data,
                Brands = await _catalogSvc.GetBrands(),
                Types = await _catalogSvc.GetTypes(),
                BrandFilterApplied = BrandFilterApplied ?? 0,
                TypesFilterApplied = TypesFilterApplied ?? 0,
                PaginationInfo = new PaginationInfo()
                {
                    ActualPage = page ?? 0,
                    ItemsPerPage = catalog.Data.Count,
                    TotalItems = catalog.Count, 
                    TotalPages = (int)Math.Ceiling(((decimal)catalog.Count / itemsPage))
                }
            };

            vm.PaginationInfo.Next = (vm.PaginationInfo.ActualPage == vm.PaginationInfo.TotalPages - 1) ? "is-disabled" : "";
            vm.PaginationInfo.Previous = (vm.PaginationInfo.ActualPage == 0) ? "is-disabled" : "";

            return View(vm);
        }
    }
}

src/Web/WebMVC/Views/Catalog/Index.cshtml
@{
    ViewData["Title"] = "Catalog";
    @model Microsoft.eShopOnContainers.WebMVC.ViewModels.CatalogViewModels.IndexViewModel
}
<section class="esh-catalog-hero">
    <div class="container">
        <img class="esh-catalog-title" src="~/images/main_banner_text.png" />
    </div>
</section>

<section class="esh-catalog-filters">
    <div class="container">
        <form asp-action="Index" asp-controller="Catalog" method="post">
            <label class="esh-catalog-label" data-title="brand">
                <select asp-for="@Model.BrandFilterApplied" asp-items="@Model.Brands" class="esh-catalog-filter"></select>
            </label>
            <label class="esh-catalog-label" data-title="type">
                <select asp-for="@Model.TypesFilterApplied" asp-items="@Model.Types" class="esh-catalog-filter"></select>
            </label>
            <input class="esh-catalog-send" type="image" src="~/images/arrow-right.svg" />
        </form>
    </div>
</section>

<div class="container">
    <div class="row">
        <br />
        @if(TempData.ContainsKey("BasketInoperativeMsg"))
        {
            <div class="alert alert-warning" role="alert">
                &nbsp;@TempData["BasketInoperativeMsg"]
            </div>
        }
    </div>

    @if (Model.CatalogItems.Count() > 0)
    {
        @Html.Partial("_pagination", Model.PaginationInfo)

        <div class="esh-catalog-items row">
            @foreach (var catalogItem in Model.CatalogItems)
            {
                <div class="esh-catalog-item col-md-4">
                    @Html.Partial("_product", catalogItem)
                </div>
            }
        </div>

        @Html.Partial("_pagination", Model.PaginationInfo)
    }
    else
    {
        <div class="esh-catalog-items row">
            THERE ARE NO RESULTS THAT MATCH YOUR SEARCH
        </div>
    }
</div>

src/Web/WebMVC/Views/Catalog/_pagination.cshtml
@model Microsoft.eShopOnContainers.WebMVC.ViewModels.Pagination.PaginationInfo

<div class="esh-pager">
    <div class="container">
        <article class="esh-pager-wrapper row">
            <nav>
                <a class="esh-pager-item esh-pager-item--navigable @Model.Previous"
                    id="Previous"                    
                    asp-controller="Catalog"
                    asp-action="Index"
                    asp-route-page="@(Model.ActualPage -1)"
                    aria-label="Previous">
                    Previous
                </a>

                <span class="esh-pager-item">
                    Showing @Model.ItemsPerPage of @Model.TotalItems products - Page @(Model.ActualPage + 1) - @Model.TotalPages
                </span>

                <a class="esh-pager-item esh-pager-item--navigable @Model.Next"
                    id="Next"                    
                    asp-controller="Catalog"
                    asp-action="Index"
                    asp-route-page="@(Model.ActualPage + 1)"
                    aria-label="Next">
                    Next
                </a>
            </nav>
        </article>
    </div>
</div>

src/Web/WebMVC/Views/Catalog/_product.cshtml
@model CatalogItem


<form asp-controller="Cart" asp-action="AddToCart">

    <img class="esh-catalog-thumbnail" src="@Model.PictureUri" />
    <input class="esh-catalog-button @((!User.Identity.IsAuthenticated) ? "is-disabled" : "")" type="submit" value="[ ADD TO CART ]" />

    <div class="esh-catalog-name">
        <span>@Model.Name</span>
    </div>
    <div class="esh-catalog-price">
        <span>@Model.Price.ToString("N2")</span>
    </div>
    <input type="hidden" asp-for="@Model.CatalogBrand" name="brand" />
    <input type="hidden" asp-for="@Model.CatalogBrandId" name="brandId" />
    <input type="hidden" asp-for="@Model.CatalogType" name="type" />
    <input type="hidden" asp-for="@Model.CatalogTypeId" name="typeId" />
    <input type="hidden" asp-for="@Model.Description" name="description" />
    <input type="hidden" asp-for="@Model.Id" name="id" />
    <input type="hidden" asp-for="@Model.Name" name="name" />
    <input type="hidden" asp-for="@Model.PictureUri" name="pictureUri" />
    <input type="hidden" asp-for="@Model.Price" name="price" />
</form>