src/Web/WebMVC/ViewModels/Order.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.eShopOnContainers.WebMVC.ViewModels.Annotations;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WebMVC.Models;

namespace Microsoft.eShopOnContainers.WebMVC.ViewModels
{
    public class Order
    {
        public string OrderNumber {get;set;}

        public DateTime Date {get;set;}

        public string Status { get; set; }

        public decimal Total {get;set;}

        public string Description { get; set; }

        [Required]
        public string City { get; set; }
        [Required]
        public string Street { get; set; }
        [Required]
        public string State { get; set; }
        [Required]
        public string Country { get; set; }

        public string ZipCode { get; set; }
        [Required]
        [DisplayName("Card number")]
        public string CardNumber { get; set; }
        [Required]
        [DisplayName("Cardholder name")]
        public string CardHolderName { get; set; }

        public DateTime CardExpiration { get; set; }
        [RegularExpression(@"(0[1-9]|1[0-2])\/[0-9]{2}", ErrorMessage = "Expiration should match a valid MM/YY value")]
        [CardExpiration(ErrorMessage = "The card is expired"), Required]
        [DisplayName("Card expiration")]
        public string CardExpirationShort { get; set; }
        [Required]
        [DisplayName("Card security number")]
        public string CardSecurityNumber { get; set; }

        public int CardTypeId { get; set; }

        public string Buyer { get; set; }

        public List<SelectListItem> ActionCodeSelectList =>
           GetActionCodesByCurrentState();

        // See the property initializer syntax below. This
        // initializes the compiler generated field for this
        // auto-implemented property.
        public List<OrderItem> OrderItems { get; } = new List<OrderItem>();

        [Required]
        public Guid RequestId { get; set; }


        public void CardExpirationShortFormat()
        {
            CardExpirationShort = CardExpiration.ToString("MM/yy");
        }

        public void CardExpirationApiFormat()
        {
            var month = CardExpirationShort.Split('/')[0];
            var year = $"20{CardExpirationShort.Split('/')[1]}";

            CardExpiration = new DateTime(int.Parse(year), int.Parse(month), 1);
        }

        private List<SelectListItem> GetActionCodesByCurrentState()
        {
            var actions = new List<OrderProcessAction>();
            switch (Status?.ToLower())
            {
                case "paid":
                    actions.Add(OrderProcessAction.Ship);
                    break;
            }

            var result = new List<SelectListItem>();
            actions.ForEach(action =>
            {
                result.Add(new SelectListItem { Text = action.Name, Value = action.Code });
            });

            return result;
        }
    }

    public enum CardType
    {
        AMEX = 1
    }
}

src/Web/WebMVC/ViewModels/OrderItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Microsoft.eShopOnContainers.WebMVC.ViewModels
{
    public class OrderItem
    {
        public int ProductId { get; set; }

        public string ProductName { get; set; }

        public decimal UnitPrice { get; set; }

        public decimal Discount { get; set; }

        public int Units { get; set; }

        public string PictureUrl { get; set; }
    }
}

src/Web/WebMVC/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.eShopOnContainers.WebMVC.Services;
using Microsoft.eShopOnContainers.WebMVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using System.Net.Http;
using Polly.CircuitBreaker;
using WebMVC.Models;

namespace Microsoft.eShopOnContainers.WebMVC.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private IOrderingService _orderSvc;
        private IBasketService _basketSvc;
        private readonly IIdentityParser<ApplicationUser> _appUserParser;
        public OrderController(IOrderingService orderSvc, IBasketService basketSvc, IIdentityParser<ApplicationUser> appUserParser)
        {
            _appUserParser = appUserParser;
            _orderSvc = orderSvc;
            _basketSvc = basketSvc;
        }

        public async Task<IActionResult> Create()
        {
            var user = _appUserParser.Parse(HttpContext.User);
            var basket = await _basketSvc.GetBasket(user);
            var order = _basketSvc.MapBasketToOrder(basket);
            var vm = _orderSvc.MapUserInfoIntoOrder(user, order);
            vm.CardExpirationShortFormat();

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(Order model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = _appUserParser.Parse(HttpContext.User);
                    var basket = _orderSvc.MapOrderToBasket(model);

                    await _basketSvc.Checkout(basket);

                    //Redirect to historic list.
                    return RedirectToAction("Index");
                }
            }
            catch(BrokenCircuitException)
            {
                ModelState.AddModelError("Error", "It was not possible to create a new order, please try later on. (Business Msg Due to Circuit-Breaker)");
            }
            return View("Create",  model);
        }

        public async Task<IActionResult> Cancel(string orderId)
        {
            await _orderSvc.CancelOrder(orderId);

            //Redirect to historic list.
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detail(string orderId)
        {
            var user = _appUserParser.Parse(HttpContext.User);

            var order = await _orderSvc.GetOrder(user, orderId);
            return View(order);
        }

        public async Task<IActionResult> Index(Order item)
        {
            var user = _appUserParser.Parse(HttpContext.User);
            var vm = await _orderSvc.GetMyOrders(user);
            return View(vm);
        }
    }
}

src/Web/WebMVC/Views/Order/Create.cshtml
@using Microsoft.eShopOnContainers.WebMVC.Services
@model Microsoft.eShopOnContainers.WebMVC.ViewModels.Order
@inject IIdentityParser<ApplicationUser> UserManager

@{
    ViewData["Title"] = "New Order";
}

@Html.Partial("_Header", new List<Header>() {
        new Header() { Controller = "Cart", Text = "Back to cart" } })
<div class="container">
    <form method="post" asp-controller="Order" asp-action="Checkout">
        <section class="esh-orders_new-section">
            <div class="row">
                @foreach (var error in ViewData.ModelState.Values.SelectMany(err => err.Errors)) {
                    <div class="alert alert-warning" role="alert">                    
                        &nbsp;@error.ErrorMessage
                    </div>
                }
            </div>
            <h4 class="esh-orders_new-title">Shipping address</h4>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Street" class="esh-orders_new-title">Address</label>
                        <input asp-for="Street" class="form-control form-input" type="text" placeholder="Street"/>
                        <span asp-validation-for="Street" class="alert alert-danger" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="City" class="esh-orders_new-title">City</label>
                        <input asp-for="City" class="form-control form-input" type="text" placeholder="City"/>
                        <span asp-validation-for="City" class="alert alert-danger" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="State" class="esh-orders_new-title">State</label>
                        <input asp-for="State" class="form-control form-input" type="text" placeholder="State"/>
                        <span asp-validation-for="State" class="alert alert-danger" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Country" class="esh-orders_new-title">Country</label>
                        <input asp-for="Country" class="form-control form-input" type="text" placeholder="Country"/>
                        <span asp-validation-for="Country" class="alert alert-danger" />
                    </div>
                </div>
            </div>
        </section>
        <section class="esh-orders_new-section">
            <h4 class="esh-orders_new-title">Payment method</h4>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="CardNumber" class="esh-orders_new-title">Card number</label>
                        <input asp-for="CardNumber" class="form-control form-input" type="text" placeholder="000000000000000"/>
                        <span asp-validation-for="CardNumber" class="alert alert-danger" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="CardHolderName" class="esh-orders_new-title">Cardholder name</label>
                        <input asp-for="CardHolderName" class="form-control form-input" type="text" placeholder="Cardholder"/>
                        <span asp-validation-for="CardHolderName" class="alert alert-danger" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="CardExpirationShort" class="esh-orders_new-title">Expiration date</label>
                        <input asp-for="CardExpirationShort" class="form-control form-input form-input-medium" type="text" placeholder="MM/YY"/>
                        <span asp-validation-for="CardExpirationShort" class="alert alert-danger" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="CardSecurityNumber" class="esh-orders_new-title">Security code</label>
                        <input asp-for="CardSecurityNumber" class="form-control form-input form-input-small" type="text" placeholder="000"/>
                        <span asp-validation-for="CardSecurityNumber" class="alert alert-danger" />
                    </div>
                </div>
            </div>
        </section>

        @await Html.PartialAsync("_OrderItems")

        <section class="esh-orders_new-section">
            <div class="form-group">
                <div class="col-md-9">
                </div>
                <div class="col-md-2">
                    <input type="submit" value="[ Place Order ]" name="action" class="btn esh-orders_new-placeOrder" />
                </div>
            </div>
        </section>
        <input asp-for="ZipCode" type="hidden" />
        <input asp-for="RequestId" type="hidden" value="@Guid.NewGuid().ToString()"/>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Web/WebMVC/Views/Order/Detail.cshtml
@using Microsoft.eShopOnContainers.WebMVC.ViewModels

@model Microsoft.eShopOnContainers.WebMVC.ViewModels.Order

@{
    ViewData["Title"] = "Order Detail";
}

<div class="esh-orders_detail">
    @Html.Partial("_Header", new List<Header>() {
        new Header() { Controller = "Catalog", Text = "Back to catalog" } })

    <div class="container">
        <section class="esh-orders_detail-section">
            <article class="esh-orders_detail-titles row">
                <section class="esh-orders_detail-title col-xs-3">Order number</section>
                <section class="esh-orders_detail-title col-xs-3">Date</section>
                <section class="esh-orders_detail-title col-xs-3">Total</section>
                <section class="esh-orders_detail-title col-xs-3">Status</section>
            </article>

            <article class="esh-orders_detail-items row">
                <section class="esh-orders_detail-item col-xs-3">@Model.OrderNumber</section>
                <section class="esh-orders_detail-item col-xs-3">@Model.Date</section>
                <section class="esh-orders_detail-item col-xs-3">$@Model.Total</section>
                <section class="esh-orders_detail-title col-xs-3">@Model.Status</section>
            </article>
        </section>
        
        <section class="esh-orders_detail-section">
            <article class="esh-orders_detail-titles row">
                <section class="esh-orders_detail-title col-xs-12">Description</section>
            </article>

            <article class="esh-orders_detail-items row">
                <section class="esh-orders_detail-item col-xs-12">@Model.Description</section>
            </article>
        </section>

        <section class="esh-orders_detail-section">
            <article class="esh-orders_detail-titles row">
                <section class="esh-orders_detail-title col-xs-12">Shiping address</section>
            </article>

            <article class="esh-orders_detail-items row">
                <section class="esh-orders_detail-item col-xs-12">@Model.Street</section>
            </article>

            <article class="esh-orders_detail-items row">
                <section class="esh-orders_detail-item col-xs-12">@Model.City</section>
            </article>

            <article class="esh-orders_detail-items row">
                <section class="esh-orders_detail-item col-xs-12">@Model.Country</section>
            </article>
        </section>

        <section class="esh-orders_detail-section">
            <article class="esh-orders_detail-titles row">
                <section class="esh-orders_detail-title col-xs-12">ORDER DETAILS</section>
            </article>

            @for (int i = 0; i < Model.OrderItems.Count; i++)
            {
                var item = Model.OrderItems[i];
                <article class="esh-orders_detail-items esh-orders_detail-items--border row">
                    <section class="esh-orders_detail-item col-md-4 hidden-md-down">
                        <img class="esh-orders_detail-image" src="@item.PictureUrl">
                    </section>
                    <section class="esh-orders_detail-item esh-orders_detail-item--middle col-xs-4">@item.ProductName</section>
                    <section class="esh-orders_detail-item esh-orders_detail-item--middle col-xs-1">$ @item.UnitPrice.ToString("N2")</section>
                    <section class="esh-orders_detail-item esh-orders_detail-item--middle col-xs-1">@item.Units</section>
                    <section class="esh-orders_detail-item esh-orders_detail-item--middle col-xs-2">$ @Math.Round(item.Units * item.UnitPrice, 2).ToString("N2")</section>
                </article>
            }
        </section>

        <section class="esh-orders_detail-section esh-orders_detail-section--right">
            <article class="esh-orders_detail-titles esh-basket-titles--clean row">
                <section class="esh-orders_detail-title col-xs-9"></section>
                <section class="esh-orders_detail-title col-xs-2">TOTAL</section>
            </article>

            <article class="esh-orders_detail-items row">
                <section class="esh-orders_detail-item col-xs-9"></section>
                <section class="esh-orders_detail-item esh-orders_detail-item--mark col-xs-2">$ @Model.Total</section>
            </article>
        </section>
    </div>
</div>

src/Web/WebMVC/Views/Order/Index.cshtml
@using Microsoft.eShopOnContainers.WebMVC.ViewModels

@model IEnumerable<Microsoft.eShopOnContainers.WebMVC.ViewModels.Order>

@{
    ViewData["Title"] = "My Orders";
}

<div class="esh-orders">
    @Html.Partial("_Header", new List<Header>() {
        new Header() { Controller = "Catalog", Text = "Back to catalog" },
        new Header() { Text = " / " },
        new Header() { Controller = "OrderManagement", Text = "Orders Management" } })

    <div class="container">
        <article class="esh-orders-titles row">
            <section class="esh-orders-title col-xs-2">Order number</section>
            <section class="esh-orders-title col-xs-4">Date</section>
            <section class="esh-orders-title col-xs-2">Total</section>
            <section class="esh-orders-title col-xs-2">Status</section>
            <section class="esh-orders-title col-xs-2"></section>
        </article>
    @if (Model != null && Model.Any())
    {
        @foreach (var item in Model)
        {
            <article class="esh-orders-items row">
                <section class="esh-orders-item col-xs-2">@Html.DisplayFor(modelItem => item.OrderNumber)</section>
                <section class="esh-orders-item col-xs-4">@Html.DisplayFor(modelItem => item.Date)</section>
                <section class="esh-orders-item col-xs-2">$ @Html.DisplayFor(modelItem => item.Total)</section>
                <section class="esh-orders-item col-xs-2">@Html.DisplayFor(modelItem => item.Status)</section>
                <section class="esh-orders-item col-xs-1">
                    <a class="esh-orders-link" asp-controller="Order" asp-action="Detail" asp-route-orderId="@item.OrderNumber">Detail</a>
                </section>
                <section class="esh-orders-item col-xs-1">
                    @if (item.Status.ToLower() == "submitted")
                    {
                        <a class="esh-orders-link" asp-controller="Order" asp-action="cancel" asp-route-orderId="@item.OrderNumber">Cancel</a>
                    }                    
                </section>
            </article>
        }
    }
    </div>
</div>
<script>
    setTimeout(function () {
        window.location.reload(true);
    }, 5000);
</script> 

src/Web/WebMVC/Views/Order/_OrderItems.cshtml
@model Microsoft.eShopOnContainers.WebMVC.ViewModels.Order


<section class="esh-orders_new-section">
    <article class="esh-orders_new-titles row">
        <section class="esh-orders_new-title col-xs-12">Order details</section>
    </article>

    @for (int i = 0; i < Model.OrderItems.Count; i++)
    {
        var item = Model.OrderItems[i];

        <article class="esh-orders_new-items esh-orders_new-items--border row">
            <section class="esh-orders_new-item col-md-4 hidden-md-down">
                <img class="esh-orders_new-image" src="@item.PictureUrl">
                <input type="hidden" value="@item.PictureUrl" name=@("orderitems[" + i + "].PictureUrl") />
            </section>
            <section class="esh-orders_new-item esh-orders_new-item--middle col-xs-4">
                @item.ProductName
                <input type="hidden" value="@item.ProductName" name=@("orderitems[" + i + "].ProductName") />
            </section>
            <section class="esh-orders_new-item esh-orders_new-item--middle col-xs-1">
                $ @item.UnitPrice.ToString("N2")
                <input type="hidden" value="@item.UnitPrice" name=@("orderitems[" + i + "].UnitPrice") />
            </section>
            <section class="esh-orders_new-item esh-orders_new-item--middle col-xs-1">
                @item.Units
                <input type="hidden" value="@item.Units" name=@("orderitems[" + i + "].Units") />
            </section>
            <section class="esh-orders_new-item esh-orders_new-item--middle col-xs-2">$ @Math.Round(item.Units * item.UnitPrice, 2).ToString("N2")</section>
        </article>
    }
</section>

<section class="esh-orders_new-section esh-orders_new-section--right">
    <article class="esh-orders_new-titles row">
        <section class="esh-orders_new-title col-xs-9"></section>
        <section class="esh-orders_new-title col-xs-2">Total</section>
    </article>

    <article class="esh-orders_new-items row">
        <section class="esh-orders_new-item col-xs-9"></section>
        <section class="esh-orders_new-item esh-orders_new-item--mark col-xs-2">
            $ @Model.Total.ToString("N2")
            <input type="hidden" value="@Model.Total" name="Total"/>
        </section>
    </article>
</section>